version: "3"

services:
  simplelogin-postfix:
    build: .
    environment:
      ALIASES_DEFAULT_DOMAIN: mydomain.com
      DB_HOST: localhost
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: simplelogin
      EMAIL_HANDLER_HOST: 127.0.0.1
      POSTFIX_FQDN: mail.mydomain.com

  sut:
    image: alpine:latest
    # Wait for Postfix to start:
    command: >
      sh -c 'for i in 1 2 3 4 5 6; do echo QUIT|nc simplelogin-postfix 25|grep "220 .* ESMTP Postfix" && break || if [ "$$i" != 6 ]; then sleep 10 ; else exit 1 ; fi; done'
    depends_on:
      - simplelogin-postfix
